# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1187, 946)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        Frame.setFont(font)
        Frame.setStyleSheet("")
        self.gridLayoutWidget = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(340, 80, 511, 420))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cur_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_20.setFont(font)
        self.cur_20.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_20.setText("")
        self.cur_20.setTextFormat(QtCore.Qt.PlainText)
        self.cur_20.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_20.setObjectName("cur_20")
        self.gridLayout.addWidget(self.cur_20, 3, 0, 1, 1)
        self.cur_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_21.setFont(font)
        self.cur_21.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_21.setText("")
        self.cur_21.setTextFormat(QtCore.Qt.PlainText)
        self.cur_21.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_21.setObjectName("cur_21")
        self.gridLayout.addWidget(self.cur_21, 3, 1, 1, 1)
        self.cur_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_12.setFont(font)
        self.cur_12.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_12.setText("")
        self.cur_12.setTextFormat(QtCore.Qt.PlainText)
        self.cur_12.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_12.setObjectName("cur_12")
        self.gridLayout.addWidget(self.cur_12, 2, 2, 1, 1)
        self.cur_00 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_00.setFont(font)
        self.cur_00.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_00.setText("")
        self.cur_00.setTextFormat(QtCore.Qt.PlainText)
        self.cur_00.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_00.setObjectName("cur_00")
        self.gridLayout.addWidget(self.cur_00, 0, 0, 1, 1)
        self.cur_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_11.setFont(font)
        self.cur_11.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_11.setText("")
        self.cur_11.setTextFormat(QtCore.Qt.PlainText)
        self.cur_11.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_11.setObjectName("cur_11")
        self.gridLayout.addWidget(self.cur_11, 2, 1, 1, 1)
        self.cur_01 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_01.setFont(font)
        self.cur_01.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_01.setText("")
        self.cur_01.setTextFormat(QtCore.Qt.PlainText)
        self.cur_01.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_01.setObjectName("cur_01")
        self.gridLayout.addWidget(self.cur_01, 0, 1, 1, 1)
        self.cur_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_10.setFont(font)
        self.cur_10.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_10.setText("")
        self.cur_10.setTextFormat(QtCore.Qt.PlainText)
        self.cur_10.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_10.setObjectName("cur_10")
        self.gridLayout.addWidget(self.cur_10, 2, 0, 1, 1)
        self.cur_02 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_02.setFont(font)
        self.cur_02.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_02.setText("")
        self.cur_02.setTextFormat(QtCore.Qt.PlainText)
        self.cur_02.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_02.setObjectName("cur_02")
        self.gridLayout.addWidget(self.cur_02, 0, 2, 1, 1)
        self.cur_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cur_22.setFont(font)
        self.cur_22.setStyleSheet("QLabel {\n"
"    border: 2px solid black; /* Viền đen 2px */\n"
"}\n"
"")
        self.cur_22.setText("")
        self.cur_22.setTextFormat(QtCore.Qt.PlainText)
        self.cur_22.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_22.setObjectName("cur_22")
        self.gridLayout.addWidget(self.cur_22, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setGeometry(QtCore.QRect(550, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lbl_Step = QtWidgets.QLabel(Frame)
        self.lbl_Step.setGeometry(QtCore.QRect(640, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Step.setFont(font)
        self.lbl_Step.setObjectName("lbl_Step")
        self.btn_Result = QtWidgets.QPushButton(Frame)
        self.btn_Result.setGeometry(QtCore.QRect(400, 620, 391, 51))
        self.btn_Result.setStyleSheet("QPushButton#btn_Result {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    font-size: 18px;            /* Cỡ chữ */\n"
"    font-weight: bold;          /* In đậm */\n"
"    padding: 12px 24px;         /* Lề trong */\n"
"    border-radius: 8px;         /* Bo góc */\n"
"    border: 2px solid #388E3C;  /* Viền đậm */\n"
"}\n"
"\n"
"QPushButton#btn_Result:hover {\n"
"    background-color: white;    /* Khi hover thì đổi màu nền */\n"
"    color: #4CAF50;            /* Đổi màu chữ */\n"
"    border: 2px solid #4CAF50; /* Viền đổi màu */\n"
"}\n"
"\n"
"QPushButton#btn_Result:pressed {\n"
"    background-color: #388E3C;  /* Khi bấm giữ */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Result.setObjectName("btn_Result")
        self.btn_Reset = QtWidgets.QPushButton(Frame)
        self.btn_Reset.setGeometry(QtCore.QRect(400, 760, 391, 51))
        self.btn_Reset.setStyleSheet("QPushButton#btn_Reset {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    font-size: 18px;            /* Cỡ chữ */\n"
"    font-weight: bold;          /* In đậm */\n"
"    padding: 12px 24px;         /* Lề trong */\n"
"    border-radius: 8px;         /* Bo góc */\n"
"    border: 2px solid #388E3C;  /* Viền đậm */\n"
"}\n"
"\n"
"QPushButton#btn_Reset:hover {\n"
"    background-color: white;    /* Khi hover thì đổi màu nền */\n"
"    color: #4CAF50;            /* Đổi màu chữ */\n"
"    border: 2px solid #4CAF50; /* Viền đổi màu */\n"
"}\n"
"\n"
"QPushButton#btn_Reset:pressed {\n"
"    background-color: #388E3C;  /* Khi bấm giữ */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Reset.setObjectName("btn_Reset")
        self.btn_Compare = QtWidgets.QPushButton(Frame)
        self.btn_Compare.setGeometry(QtCore.QRect(400, 690, 391, 51))
        self.btn_Compare.setStyleSheet("QPushButton#btn_Compare {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    font-size: 18px;            /* Cỡ chữ */\n"
"    font-weight: bold;          /* In đậm */\n"
"    padding: 12px 24px;         /* Lề trong */\n"
"    border-radius: 8px;         /* Bo góc */\n"
"    border: 2px solid #388E3C;  /* Viền đậm */\n"
"}\n"
"\n"
"QPushButton#btn_Compare:hover {\n"
"    background-color: white;    /* Khi hover thì đổi màu nền */\n"
"    color: #4CAF50;            /* Đổi màu chữ */\n"
"    border: 2px solid #4CAF50; /* Viền đổi màu */\n"
"}\n"
"\n"
"QPushButton#btn_Compare:pressed {\n"
"    background-color: #388E3C;  /* Khi bấm giữ */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Compare.setObjectName("btn_Compare")
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 241, 361))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    background-color: #f9f9f9;\n"
"    padding: 10px;\n"
"    font: 9pt \"Segoe UI\";  /* Giữ font chữ cỡ 9 */\n"
"    color: #333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 3px 10px;\n"
"    border-radius: 5px;\n"
"    font: bold 9pt \"Segoe UI\"; /* Tiêu đề cũng font 9 */\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 241, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Bfs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Bfs.setFont(font)
        self.btn_Bfs.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Bfs.setObjectName("btn_Bfs")
        self.verticalLayout.addWidget(self.btn_Bfs)
        self.btn_Dfs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Dfs.setFont(font)
        self.btn_Dfs.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Dfs.setObjectName("btn_Dfs")
        self.verticalLayout.addWidget(self.btn_Dfs)
        self.btn_Ucs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Ucs.setFont(font)
        self.btn_Ucs.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Ucs.setObjectName("btn_Ucs")
        self.verticalLayout.addWidget(self.btn_Ucs)
        self.btn_Ids = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Ids.setFont(font)
        self.btn_Ids.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Ids.setObjectName("btn_Ids")
        self.verticalLayout.addWidget(self.btn_Ids)
        self.groupBox_2 = QtWidgets.QGroupBox(Frame)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 420, 241, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    background-color: #f9f9f9;\n"
"    padding: 10px;\n"
"    font: 9pt \"Segoe UI\";  /* Giữ font chữ cỡ 9 */\n"
"    color: #333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 3px 10px;\n"
"    border-radius: 5px;\n"
"    font: bold 9pt \"Segoe UI\"; /* Tiêu đề cũng font 9 */\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 241, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_Astar = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Astar.setFont(font)
        self.btn_Astar.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Astar.setObjectName("btn_Astar")
        self.verticalLayout_2.addWidget(self.btn_Astar)
        self.btn_Greedy = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Greedy.setFont(font)
        self.btn_Greedy.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Greedy.setObjectName("btn_Greedy")
        self.verticalLayout_2.addWidget(self.btn_Greedy)
        self.btn_IdaStar = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_IdaStar.setFont(font)
        self.btn_IdaStar.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_IdaStar.setObjectName("btn_IdaStar")
        self.verticalLayout_2.addWidget(self.btn_IdaStar)
        self.groupBox_4 = QtWidgets.QGroupBox(Frame)
        self.groupBox_4.setGeometry(QtCore.QRect(930, 10, 241, 361))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    background-color: #f9f9f9;\n"
"    padding: 10px;\n"
"    font: 9pt \"Segoe UI\";  /* Giữ font chữ cỡ 9 */\n"
"    color: #333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 3px 10px;\n"
"    border-radius: 5px;\n"
"    font: bold 9pt \"Segoe UI\"; /* Tiêu đề cũng font 9 */\n"
"}\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 40, 241, 311))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Shc = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Shc.setFont(font)
        self.btn_Shc.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Shc.setObjectName("btn_Shc")
        self.verticalLayout_4.addWidget(self.btn_Shc)
        self.btn_Sahc = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Sahc.setFont(font)
        self.btn_Sahc.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Sahc.setObjectName("btn_Sahc")
        self.verticalLayout_4.addWidget(self.btn_Sahc)
        self.btn_Sa = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Sa.setFont(font)
        self.btn_Sa.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Sa.setObjectName("btn_Sa")
        self.verticalLayout_4.addWidget(self.btn_Sa)
        self.btn_StochchaticHC = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_StochchaticHC.setFont(font)
        self.btn_StochchaticHC.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_StochchaticHC.setObjectName("btn_StochchaticHC")
        self.verticalLayout_4.addWidget(self.btn_StochchaticHC)
        self.btn_Bs = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Bs.setFont(font)
        self.btn_Bs.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Bs.setObjectName("btn_Bs")
        self.verticalLayout_4.addWidget(self.btn_Bs)
        self.btn_Ga = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Ga.setFont(font)
        self.btn_Ga.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Ga.setObjectName("btn_Ga")
        self.verticalLayout_4.addWidget(self.btn_Ga)
        self.groupBox_3 = QtWidgets.QGroupBox(Frame)
        self.groupBox_3.setGeometry(QtCore.QRect(930, 420, 241, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    background-color: #f9f9f9;\n"
"    padding: 10px;\n"
"    font: 9pt \"Segoe UI\";  /* Giữ font chữ cỡ 9 */\n"
"    color: #333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 3px 10px;\n"
"    border-radius: 5px;\n"
"    font: bold 9pt \"Segoe UI\"; /* Tiêu đề cũng font 9 */\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 50, 241, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_AoStar = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_AoStar.setFont(font)
        self.btn_AoStar.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_AoStar.setObjectName("btn_AoStar")
        self.verticalLayout_5.addWidget(self.btn_AoStar)
        self.btn_Nos = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Nos.setFont(font)
        self.btn_Nos.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Nos.setObjectName("btn_Nos")
        self.verticalLayout_5.addWidget(self.btn_Nos)
        self.btn_Pos = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Pos.setFont(font)
        self.btn_Pos.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Pos.setObjectName("btn_Pos")
        self.verticalLayout_5.addWidget(self.btn_Pos)
        self.groupBox_5 = QtWidgets.QGroupBox(Frame)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 690, 241, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    background-color: #f9f9f9;\n"
"    padding: 10px;\n"
"    font: 9pt \"Segoe UI\";  /* Giữ font chữ cỡ 9 */\n"
"    color: #333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 3px 10px;\n"
"    border-radius: 5px;\n"
"    font: bold 9pt \"Segoe UI\"; /* Tiêu đề cũng font 9 */\n"
"}\n"
"")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 50, 241, 171))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_Test = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Test.setFont(font)
        self.btn_Test.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Test.setObjectName("btn_Test")
        self.verticalLayout_3.addWidget(self.btn_Test)
        self.btn_Backtracking = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_Backtracking.setFont(font)
        self.btn_Backtracking.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Backtracking.setObjectName("btn_Backtracking")
        self.verticalLayout_3.addWidget(self.btn_Backtracking)
        self.btn_AC3 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_AC3.setFont(font)
        self.btn_AC3.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_AC3.setObjectName("btn_AC3")
        self.verticalLayout_3.addWidget(self.btn_AC3)
        self.groupBox_6 = QtWidgets.QGroupBox(Frame)
        self.groupBox_6.setGeometry(QtCore.QRect(930, 690, 241, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    background-color: #f9f9f9;\n"
"    padding: 10px;\n"
"    font: 9pt \"Segoe UI\";  /* Giữ font chữ cỡ 9 */\n"
"    color: #333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 3px 10px;\n"
"    border-radius: 5px;\n"
"    font: bold 9pt \"Segoe UI\"; /* Tiêu đề cũng font 9 */\n"
"}\n"
"")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 50, 241, 171))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_QLearning = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_QLearning.setFont(font)
        self.btn_QLearning.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Màu nền xanh lá */\n"
"    color: white;               /* Màu chữ trắng */\n"
"    border-radius: 10px;        /* Bo góc */\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;    /* Khi hover, đổi nền thành trắng */\n"
"    color: #4CAF50;            /* Chữ đổi thành màu xanh lá */\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39; /* Màu nền khi nhấn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_QLearning.setObjectName("btn_QLearning")
        self.verticalLayout_7.addWidget(self.btn_QLearning)
        self.lbl_title = QtWidgets.QLabel(Frame)
        self.lbl_title.setGeometry(QtCore.QRect(380, 10, 421, 61))
        self.lbl_title.setStyleSheet("QLabel {\n"
"    background-color: #f0f4f7;\n"
"    color: #2c3e50;\n"
"    font: bold 25px \"Segoe UI\";\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.lbl_title.setText("")
        self.lbl_title.setObjectName("lbl_title")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_10.setText(_translate("Frame", "STEP :"))
        self.lbl_Step.setText(_translate("Frame", "0"))
        self.btn_Result.setText(_translate("Frame", "DETAILED STEPS"))
        self.btn_Reset.setText(_translate("Frame", "RESET"))
        self.btn_Compare.setText(_translate("Frame", "COMPARE"))
        self.groupBox.setTitle(_translate("Frame", "Uninformed Search Algorithms"))
        self.btn_Bfs.setText(_translate("Frame", "BFS"))
        self.btn_Dfs.setText(_translate("Frame", "DFS"))
        self.btn_Ucs.setText(_translate("Frame", "UCS"))
        self.btn_Ids.setText(_translate("Frame", "IDS"))
        self.groupBox_2.setTitle(_translate("Frame", "Informed Search Algorithms"))
        self.btn_Astar.setText(_translate("Frame", "A*"))
        self.btn_Greedy.setText(_translate("Frame", "Greedy"))
        self.btn_IdaStar.setText(_translate("Frame", "IDA*"))
        self.groupBox_4.setTitle(_translate("Frame", "Local Search Algorithms"))
        self.btn_Shc.setText(_translate("Frame", "SHC"))
        self.btn_Sahc.setText(_translate("Frame", "SAHC"))
        self.btn_Sa.setText(_translate("Frame", "SA"))
        self.btn_StochchaticHC.setText(_translate("Frame", "StochasticHC"))
        self.btn_Bs.setText(_translate("Frame", "BeamSearch"))
        self.btn_Ga.setText(_translate("Frame", "GA"))
        self.groupBox_3.setTitle(_translate("Frame", "Searching with Nondeterministic "))
        self.btn_AoStar.setText(_translate("Frame", "AO*"))
        self.btn_Nos.setText(_translate("Frame", "NOS"))
        self.btn_Pos.setText(_translate("Frame", "POS"))
        self.groupBox_5.setTitle(_translate("Frame", " Constraint Satisfaction Problem"))
        self.btn_Test.setText(_translate("Frame", "Test"))
        self.btn_Backtracking.setText(_translate("Frame", "Backtracking"))
        self.btn_AC3.setText(_translate("Frame", "AC3"))
        self.groupBox_6.setTitle(_translate("Frame", "Reinforcement Learning"))
        self.btn_QLearning.setText(_translate("Frame", "Q-Learning"))
