# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1313, 809)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(310, 1170, 201, 141))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_73 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_73.setObjectName("label_73")
        self.gridLayout_9.addWidget(self.label_73, 1, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_74.setObjectName("label_74")
        self.gridLayout_9.addWidget(self.label_74, 1, 2, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_75.setObjectName("label_75")
        self.gridLayout_9.addWidget(self.label_75, 0, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_76.setObjectName("label_76")
        self.gridLayout_9.addWidget(self.label_76, 0, 2, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_77.setObjectName("label_77")
        self.gridLayout_9.addWidget(self.label_77, 0, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_78.setObjectName("label_78")
        self.gridLayout_9.addWidget(self.label_78, 1, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_79.setObjectName("label_79")
        self.gridLayout_9.addWidget(self.label_79, 2, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_80.setObjectName("label_80")
        self.gridLayout_9.addWidget(self.label_80, 2, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_81.setObjectName("label_81")
        self.gridLayout_9.addWidget(self.label_81, 2, 2, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(310, 1000, 201, 141))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_100 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_100.setObjectName("label_100")
        self.gridLayout_12.addWidget(self.label_100, 0, 0, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_101.setObjectName("label_101")
        self.gridLayout_12.addWidget(self.label_101, 1, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_102.setObjectName("label_102")
        self.gridLayout_12.addWidget(self.label_102, 0, 2, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_103.setObjectName("label_103")
        self.gridLayout_12.addWidget(self.label_103, 0, 1, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_104.setObjectName("label_104")
        self.gridLayout_12.addWidget(self.label_104, 2, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_105.setObjectName("label_105")
        self.gridLayout_12.addWidget(self.label_105, 1, 0, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_106.setObjectName("label_106")
        self.gridLayout_12.addWidget(self.label_106, 2, 2, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_107.setObjectName("label_107")
        self.gridLayout_12.addWidget(self.label_107, 2, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_108.setObjectName("label_108")
        self.gridLayout_12.addWidget(self.label_108, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 471, 731))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 8px;\n"
"    margin-top: 20px;\n"
"    background-color: #f2faff;\n"
"    font: bold 12pt \"Segoe UI\";\n"
"    color: #003366;\n"
"    padding: 10px; /* Thêm padding để nội dung không bị đè */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 5px 15px;\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 201, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.s04 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s04.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s04.setText("")
        self.s04.setObjectName("s04")
        self.gridLayout.addWidget(self.s04, 1, 1, 1, 1)
        self.s05 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s05.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s05.setText("")
        self.s05.setObjectName("s05")
        self.gridLayout.addWidget(self.s05, 1, 2, 1, 1)
        self.s00 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s00.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s00.setText("")
        self.s00.setObjectName("s00")
        self.gridLayout.addWidget(self.s00, 0, 0, 1, 1)
        self.s02 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s02.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s02.setText("")
        self.s02.setObjectName("s02")
        self.gridLayout.addWidget(self.s02, 0, 2, 1, 1)
        self.s01 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s01.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s01.setText("")
        self.s01.setObjectName("s01")
        self.gridLayout.addWidget(self.s01, 0, 1, 1, 1)
        self.s03 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s03.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s03.setText("")
        self.s03.setObjectName("s03")
        self.gridLayout.addWidget(self.s03, 1, 0, 1, 1)
        self.s06 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s06.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s06.setText("")
        self.s06.setObjectName("s06")
        self.gridLayout.addWidget(self.s06, 2, 0, 1, 1)
        self.s07 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s07.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s07.setText("")
        self.s07.setObjectName("s07")
        self.gridLayout.addWidget(self.s07, 2, 1, 1, 1)
        self.s08 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.s08.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s08.setText("")
        self.s08.setObjectName("s08")
        self.gridLayout.addWidget(self.s08, 2, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 50, 201, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.s44 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s44.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s44.setText("")
        self.s44.setObjectName("s44")
        self.gridLayout_2.addWidget(self.s44, 1, 1, 1, 1)
        self.s45 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s45.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s45.setText("")
        self.s45.setObjectName("s45")
        self.gridLayout_2.addWidget(self.s45, 1, 2, 1, 1)
        self.s40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s40.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s40.setText("")
        self.s40.setObjectName("s40")
        self.gridLayout_2.addWidget(self.s40, 0, 0, 1, 1)
        self.s42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s42.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s42.setText("")
        self.s42.setObjectName("s42")
        self.gridLayout_2.addWidget(self.s42, 0, 2, 1, 1)
        self.s41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s41.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s41.setText("")
        self.s41.setObjectName("s41")
        self.gridLayout_2.addWidget(self.s41, 0, 1, 1, 1)
        self.s43 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s43.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s43.setText("")
        self.s43.setObjectName("s43")
        self.gridLayout_2.addWidget(self.s43, 1, 0, 1, 1)
        self.s46 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s46.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s46.setText("")
        self.s46.setObjectName("s46")
        self.gridLayout_2.addWidget(self.s46, 2, 0, 1, 1)
        self.s47 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s47.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s47.setText("")
        self.s47.setObjectName("s47")
        self.gridLayout_2.addWidget(self.s47, 2, 1, 1, 1)
        self.s48 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.s48.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s48.setText("")
        self.s48.setObjectName("s48")
        self.gridLayout_2.addWidget(self.s48, 2, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 220, 201, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.s13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s13.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s13.setText("")
        self.s13.setObjectName("s13")
        self.gridLayout_3.addWidget(self.s13, 1, 0, 1, 1)
        self.s16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s16.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s16.setText("")
        self.s16.setObjectName("s16")
        self.gridLayout_3.addWidget(self.s16, 2, 0, 1, 1)
        self.s17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s17.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s17.setText("")
        self.s17.setObjectName("s17")
        self.gridLayout_3.addWidget(self.s17, 2, 1, 1, 1)
        self.s18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s18.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s18.setText("")
        self.s18.setObjectName("s18")
        self.gridLayout_3.addWidget(self.s18, 2, 2, 1, 1)
        self.s14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s14.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s14.setText("")
        self.s14.setObjectName("s14")
        self.gridLayout_3.addWidget(self.s14, 1, 1, 1, 1)
        self.s15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s15.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s15.setText("")
        self.s15.setObjectName("s15")
        self.gridLayout_3.addWidget(self.s15, 1, 2, 1, 1)
        self.s12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s12.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s12.setText("")
        self.s12.setObjectName("s12")
        self.gridLayout_3.addWidget(self.s12, 0, 2, 1, 1)
        self.s11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s11.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s11.setText("")
        self.s11.setObjectName("s11")
        self.gridLayout_3.addWidget(self.s11, 0, 1, 1, 1)
        self.s10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.s10.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s10.setText("")
        self.s10.setObjectName("s10")
        self.gridLayout_3.addWidget(self.s10, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 390, 201, 151))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.s23 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s23.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s23.setText("")
        self.s23.setObjectName("s23")
        self.gridLayout_4.addWidget(self.s23, 1, 0, 1, 1)
        self.s26 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s26.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s26.setText("")
        self.s26.setObjectName("s26")
        self.gridLayout_4.addWidget(self.s26, 2, 0, 1, 1)
        self.s27 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s27.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s27.setText("")
        self.s27.setObjectName("s27")
        self.gridLayout_4.addWidget(self.s27, 2, 1, 1, 1)
        self.s28 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s28.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s28.setText("")
        self.s28.setObjectName("s28")
        self.gridLayout_4.addWidget(self.s28, 2, 2, 1, 1)
        self.s24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s24.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s24.setText("")
        self.s24.setObjectName("s24")
        self.gridLayout_4.addWidget(self.s24, 1, 1, 1, 1)
        self.s25 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s25.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s25.setText("")
        self.s25.setObjectName("s25")
        self.gridLayout_4.addWidget(self.s25, 1, 2, 1, 1)
        self.s22 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s22.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s22.setText("")
        self.s22.setObjectName("s22")
        self.gridLayout_4.addWidget(self.s22, 0, 2, 1, 1)
        self.s21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s21.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s21.setText("")
        self.s21.setObjectName("s21")
        self.gridLayout_4.addWidget(self.s21, 0, 1, 1, 1)
        self.s20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.s20.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s20.setText("")
        self.s20.setObjectName("s20")
        self.gridLayout_4.addWidget(self.s20, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 570, 201, 151))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.s33 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s33.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s33.setText("")
        self.s33.setObjectName("s33")
        self.gridLayout_10.addWidget(self.s33, 1, 0, 1, 1)
        self.s36 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s36.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s36.setText("")
        self.s36.setObjectName("s36")
        self.gridLayout_10.addWidget(self.s36, 2, 0, 1, 1)
        self.s37 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s37.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s37.setText("")
        self.s37.setObjectName("s37")
        self.gridLayout_10.addWidget(self.s37, 2, 1, 1, 1)
        self.s38 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s38.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s38.setText("")
        self.s38.setObjectName("s38")
        self.gridLayout_10.addWidget(self.s38, 2, 2, 1, 1)
        self.s34 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s34.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s34.setText("")
        self.s34.setObjectName("s34")
        self.gridLayout_10.addWidget(self.s34, 1, 1, 1, 1)
        self.s35 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s35.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s35.setText("")
        self.s35.setObjectName("s35")
        self.gridLayout_10.addWidget(self.s35, 1, 2, 1, 1)
        self.s32 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s32.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s32.setText("")
        self.s32.setObjectName("s32")
        self.gridLayout_10.addWidget(self.s32, 0, 2, 1, 1)
        self.s31 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s31.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s31.setText("")
        self.s31.setObjectName("s31")
        self.gridLayout_10.addWidget(self.s31, 0, 1, 1, 1)
        self.s30 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.s30.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s30.setText("")
        self.s30.setObjectName("s30")
        self.gridLayout_10.addWidget(self.s30, 0, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(250, 220, 201, 151))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.s53 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s53.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s53.setText("")
        self.s53.setObjectName("s53")
        self.gridLayout_11.addWidget(self.s53, 1, 0, 1, 1)
        self.s56 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s56.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s56.setText("")
        self.s56.setObjectName("s56")
        self.gridLayout_11.addWidget(self.s56, 2, 0, 1, 1)
        self.s58 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s58.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s58.setText("")
        self.s58.setObjectName("s58")
        self.gridLayout_11.addWidget(self.s58, 2, 2, 1, 1)
        self.s57 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s57.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s57.setText("")
        self.s57.setObjectName("s57")
        self.gridLayout_11.addWidget(self.s57, 2, 1, 1, 1)
        self.s52 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s52.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s52.setText("")
        self.s52.setObjectName("s52")
        self.gridLayout_11.addWidget(self.s52, 0, 2, 1, 1)
        self.s54 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s54.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s54.setText("")
        self.s54.setObjectName("s54")
        self.gridLayout_11.addWidget(self.s54, 1, 1, 1, 1)
        self.s55 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s55.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s55.setText("")
        self.s55.setObjectName("s55")
        self.gridLayout_11.addWidget(self.s55, 1, 2, 1, 1)
        self.s50 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s50.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s50.setText("")
        self.s50.setObjectName("s50")
        self.gridLayout_11.addWidget(self.s50, 0, 0, 1, 1)
        self.s51 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.s51.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s51.setText("")
        self.s51.setObjectName("s51")
        self.gridLayout_11.addWidget(self.s51, 0, 1, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(250, 390, 201, 151))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.s63 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s63.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s63.setText("")
        self.s63.setObjectName("s63")
        self.gridLayout_13.addWidget(self.s63, 1, 0, 1, 1)
        self.s66 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s66.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s66.setText("")
        self.s66.setObjectName("s66")
        self.gridLayout_13.addWidget(self.s66, 2, 0, 1, 1)
        self.s67 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s67.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s67.setText("")
        self.s67.setObjectName("s67")
        self.gridLayout_13.addWidget(self.s67, 2, 1, 1, 1)
        self.s68 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s68.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s68.setText("")
        self.s68.setObjectName("s68")
        self.gridLayout_13.addWidget(self.s68, 2, 2, 1, 1)
        self.s64 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s64.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s64.setText("")
        self.s64.setObjectName("s64")
        self.gridLayout_13.addWidget(self.s64, 1, 1, 1, 1)
        self.s65 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s65.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s65.setText("")
        self.s65.setObjectName("s65")
        self.gridLayout_13.addWidget(self.s65, 1, 2, 1, 1)
        self.s62 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s62.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s62.setText("")
        self.s62.setObjectName("s62")
        self.gridLayout_13.addWidget(self.s62, 0, 2, 1, 1)
        self.s61 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s61.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s61.setText("")
        self.s61.setObjectName("s61")
        self.gridLayout_13.addWidget(self.s61, 0, 1, 1, 1)
        self.s60 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.s60.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s60.setText("")
        self.s60.setObjectName("s60")
        self.gridLayout_13.addWidget(self.s60, 0, 0, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(250, 570, 201, 151))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.s73 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s73.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s73.setText("")
        self.s73.setObjectName("s73")
        self.gridLayout_14.addWidget(self.s73, 1, 0, 1, 1)
        self.s76 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s76.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s76.setText("")
        self.s76.setObjectName("s76")
        self.gridLayout_14.addWidget(self.s76, 2, 0, 1, 1)
        self.s77 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s77.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s77.setText("")
        self.s77.setObjectName("s77")
        self.gridLayout_14.addWidget(self.s77, 2, 1, 1, 1)
        self.s78 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s78.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s78.setText("")
        self.s78.setObjectName("s78")
        self.gridLayout_14.addWidget(self.s78, 2, 2, 1, 1)
        self.s74 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s74.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s74.setText("")
        self.s74.setObjectName("s74")
        self.gridLayout_14.addWidget(self.s74, 1, 1, 1, 1)
        self.s75 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s75.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s75.setText("")
        self.s75.setObjectName("s75")
        self.gridLayout_14.addWidget(self.s75, 1, 2, 1, 1)
        self.s72 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s72.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s72.setText("")
        self.s72.setObjectName("s72")
        self.gridLayout_14.addWidget(self.s72, 0, 2, 1, 1)
        self.s71 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s71.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s71.setText("")
        self.s71.setObjectName("s71")
        self.gridLayout_14.addWidget(self.s71, 0, 1, 1, 1)
        self.s70 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.s70.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.s70.setText("")
        self.s70.setObjectName("s70")
        self.gridLayout_14.addWidget(self.s70, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Frame)
        self.groupBox_3.setGeometry(QtCore.QRect(830, 10, 471, 731))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 8px;\n"
"    margin-top: 20px;\n"
"    background-color: #f2faff;\n"
"    font: bold 12pt \"Segoe UI\";\n"
"    color: #003366;\n"
"    padding: 10px; /* Thêm padding để nội dung không bị đè */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 5px 15px;\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(10, 50, 201, 151))
        self.gridLayoutWidget_19.setObjectName("gridLayoutWidget_19")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gridLayoutWidget_19)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.d04 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d04.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d04.setText("")
        self.d04.setObjectName("d04")
        self.gridLayout_23.addWidget(self.d04, 1, 1, 1, 1)
        self.d05 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d05.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d05.setText("")
        self.d05.setObjectName("d05")
        self.gridLayout_23.addWidget(self.d05, 1, 2, 1, 1)
        self.d00 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d00.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d00.setText("")
        self.d00.setObjectName("d00")
        self.gridLayout_23.addWidget(self.d00, 0, 0, 1, 1)
        self.d02 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d02.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d02.setText("")
        self.d02.setObjectName("d02")
        self.gridLayout_23.addWidget(self.d02, 0, 2, 1, 1)
        self.d01 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d01.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d01.setText("")
        self.d01.setObjectName("d01")
        self.gridLayout_23.addWidget(self.d01, 0, 1, 1, 1)
        self.d03 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d03.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d03.setText("")
        self.d03.setObjectName("d03")
        self.gridLayout_23.addWidget(self.d03, 1, 0, 1, 1)
        self.d06 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d06.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d06.setText("")
        self.d06.setObjectName("d06")
        self.gridLayout_23.addWidget(self.d06, 2, 0, 1, 1)
        self.d07 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d07.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d07.setText("")
        self.d07.setObjectName("d07")
        self.gridLayout_23.addWidget(self.d07, 2, 1, 1, 1)
        self.d08 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.d08.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d08.setText("")
        self.d08.setObjectName("d08")
        self.gridLayout_23.addWidget(self.d08, 2, 2, 1, 1)
        self.gridLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(250, 50, 201, 151))
        self.gridLayoutWidget_20.setObjectName("gridLayoutWidget_20")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.gridLayoutWidget_20)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.d44 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d44.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d44.setText("")
        self.d44.setObjectName("d44")
        self.gridLayout_24.addWidget(self.d44, 1, 1, 1, 1)
        self.d45 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d45.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d45.setText("")
        self.d45.setObjectName("d45")
        self.gridLayout_24.addWidget(self.d45, 1, 2, 1, 1)
        self.d40 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d40.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d40.setText("")
        self.d40.setObjectName("d40")
        self.gridLayout_24.addWidget(self.d40, 0, 0, 1, 1)
        self.d42 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d42.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d42.setText("")
        self.d42.setObjectName("d42")
        self.gridLayout_24.addWidget(self.d42, 0, 2, 1, 1)
        self.d41 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d41.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d41.setText("")
        self.d41.setObjectName("d41")
        self.gridLayout_24.addWidget(self.d41, 0, 1, 1, 1)
        self.d43 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d43.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d43.setText("")
        self.d43.setObjectName("d43")
        self.gridLayout_24.addWidget(self.d43, 1, 0, 1, 1)
        self.d46 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d46.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d46.setText("")
        self.d46.setObjectName("d46")
        self.gridLayout_24.addWidget(self.d46, 2, 0, 1, 1)
        self.d47 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d47.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d47.setText("")
        self.d47.setObjectName("d47")
        self.gridLayout_24.addWidget(self.d47, 2, 1, 1, 1)
        self.d48 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.d48.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d48.setText("")
        self.d48.setObjectName("d48")
        self.gridLayout_24.addWidget(self.d48, 2, 2, 1, 1)
        self.gridLayoutWidget_22 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_22.setGeometry(QtCore.QRect(10, 390, 201, 151))
        self.gridLayoutWidget_22.setObjectName("gridLayoutWidget_22")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.gridLayoutWidget_22)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.d23 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d23.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d23.setText("")
        self.d23.setObjectName("d23")
        self.gridLayout_26.addWidget(self.d23, 1, 0, 1, 1)
        self.d26 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d26.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d26.setText("")
        self.d26.setObjectName("d26")
        self.gridLayout_26.addWidget(self.d26, 2, 0, 1, 1)
        self.d27 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d27.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d27.setText("")
        self.d27.setObjectName("d27")
        self.gridLayout_26.addWidget(self.d27, 2, 1, 1, 1)
        self.d28 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d28.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d28.setText("")
        self.d28.setObjectName("d28")
        self.gridLayout_26.addWidget(self.d28, 2, 2, 1, 1)
        self.d24 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d24.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d24.setText("")
        self.d24.setObjectName("d24")
        self.gridLayout_26.addWidget(self.d24, 1, 1, 1, 1)
        self.d25 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d25.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d25.setText("")
        self.d25.setObjectName("d25")
        self.gridLayout_26.addWidget(self.d25, 1, 2, 1, 1)
        self.d22 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d22.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d22.setText("")
        self.d22.setObjectName("d22")
        self.gridLayout_26.addWidget(self.d22, 0, 2, 1, 1)
        self.d21 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d21.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d21.setText("")
        self.d21.setObjectName("d21")
        self.gridLayout_26.addWidget(self.d21, 0, 1, 1, 1)
        self.d20 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.d20.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d20.setText("")
        self.d20.setObjectName("d20")
        self.gridLayout_26.addWidget(self.d20, 0, 0, 1, 1)
        self.gridLayoutWidget_23 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_23.setGeometry(QtCore.QRect(10, 570, 201, 151))
        self.gridLayoutWidget_23.setObjectName("gridLayoutWidget_23")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.gridLayoutWidget_23)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.d33 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d33.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d33.setText("")
        self.d33.setObjectName("d33")
        self.gridLayout_27.addWidget(self.d33, 1, 0, 1, 1)
        self.d36 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d36.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d36.setText("")
        self.d36.setObjectName("d36")
        self.gridLayout_27.addWidget(self.d36, 2, 0, 1, 1)
        self.d37 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d37.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d37.setText("")
        self.d37.setObjectName("d37")
        self.gridLayout_27.addWidget(self.d37, 2, 1, 1, 1)
        self.d38 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d38.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d38.setText("")
        self.d38.setObjectName("d38")
        self.gridLayout_27.addWidget(self.d38, 2, 2, 1, 1)
        self.d34 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d34.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d34.setText("")
        self.d34.setObjectName("d34")
        self.gridLayout_27.addWidget(self.d34, 1, 1, 1, 1)
        self.d35 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d35.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d35.setText("")
        self.d35.setObjectName("d35")
        self.gridLayout_27.addWidget(self.d35, 1, 2, 1, 1)
        self.d32 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d32.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d32.setText("")
        self.d32.setObjectName("d32")
        self.gridLayout_27.addWidget(self.d32, 0, 2, 1, 1)
        self.d31 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d31.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d31.setText("")
        self.d31.setObjectName("d31")
        self.gridLayout_27.addWidget(self.d31, 0, 1, 1, 1)
        self.d30 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.d30.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d30.setText("")
        self.d30.setObjectName("d30")
        self.gridLayout_27.addWidget(self.d30, 0, 0, 1, 1)
        self.gridLayoutWidget_24 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_24.setGeometry(QtCore.QRect(250, 220, 201, 151))
        self.gridLayoutWidget_24.setObjectName("gridLayoutWidget_24")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.gridLayoutWidget_24)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.d53 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d53.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d53.setText("")
        self.d53.setObjectName("d53")
        self.gridLayout_28.addWidget(self.d53, 1, 0, 1, 1)
        self.d56 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d56.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d56.setText("")
        self.d56.setObjectName("d56")
        self.gridLayout_28.addWidget(self.d56, 2, 0, 1, 1)
        self.d58 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d58.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d58.setText("")
        self.d58.setObjectName("d58")
        self.gridLayout_28.addWidget(self.d58, 2, 2, 1, 1)
        self.d57 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d57.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d57.setText("")
        self.d57.setObjectName("d57")
        self.gridLayout_28.addWidget(self.d57, 2, 1, 1, 1)
        self.d52 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d52.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d52.setText("")
        self.d52.setObjectName("d52")
        self.gridLayout_28.addWidget(self.d52, 0, 2, 1, 1)
        self.d54 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d54.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d54.setText("")
        self.d54.setObjectName("d54")
        self.gridLayout_28.addWidget(self.d54, 1, 1, 1, 1)
        self.d55 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d55.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d55.setText("")
        self.d55.setObjectName("d55")
        self.gridLayout_28.addWidget(self.d55, 1, 2, 1, 1)
        self.d50 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d50.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d50.setText("")
        self.d50.setObjectName("d50")
        self.gridLayout_28.addWidget(self.d50, 0, 0, 1, 1)
        self.d51 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.d51.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d51.setText("")
        self.d51.setObjectName("d51")
        self.gridLayout_28.addWidget(self.d51, 0, 1, 1, 1)
        self.gridLayoutWidget_25 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_25.setGeometry(QtCore.QRect(250, 390, 201, 151))
        self.gridLayoutWidget_25.setObjectName("gridLayoutWidget_25")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.gridLayoutWidget_25)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.d63 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d63.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d63.setText("")
        self.d63.setObjectName("d63")
        self.gridLayout_29.addWidget(self.d63, 1, 0, 1, 1)
        self.d66 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d66.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d66.setText("")
        self.d66.setObjectName("d66")
        self.gridLayout_29.addWidget(self.d66, 2, 0, 1, 1)
        self.d67 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d67.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d67.setText("")
        self.d67.setObjectName("d67")
        self.gridLayout_29.addWidget(self.d67, 2, 1, 1, 1)
        self.d68 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d68.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d68.setText("")
        self.d68.setObjectName("d68")
        self.gridLayout_29.addWidget(self.d68, 2, 2, 1, 1)
        self.d64 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d64.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d64.setText("")
        self.d64.setObjectName("d64")
        self.gridLayout_29.addWidget(self.d64, 1, 1, 1, 1)
        self.d65 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d65.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d65.setText("")
        self.d65.setObjectName("d65")
        self.gridLayout_29.addWidget(self.d65, 1, 2, 1, 1)
        self.d62 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d62.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d62.setText("")
        self.d62.setObjectName("d62")
        self.gridLayout_29.addWidget(self.d62, 0, 2, 1, 1)
        self.d61 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d61.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d61.setText("")
        self.d61.setObjectName("d61")
        self.gridLayout_29.addWidget(self.d61, 0, 1, 1, 1)
        self.d60 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.d60.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 3px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d60.setText("")
        self.d60.setObjectName("d60")
        self.gridLayout_29.addWidget(self.d60, 0, 0, 1, 1)
        self.gridLayoutWidget_26 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_26.setGeometry(QtCore.QRect(250, 570, 201, 151))
        self.gridLayoutWidget_26.setObjectName("gridLayoutWidget_26")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.gridLayoutWidget_26)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.d73 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d73.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d73.setText("")
        self.d73.setObjectName("d73")
        self.gridLayout_30.addWidget(self.d73, 1, 0, 1, 1)
        self.d76 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d76.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d76.setText("")
        self.d76.setObjectName("d76")
        self.gridLayout_30.addWidget(self.d76, 2, 0, 1, 1)
        self.d77 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d77.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d77.setText("")
        self.d77.setObjectName("d77")
        self.gridLayout_30.addWidget(self.d77, 2, 1, 1, 1)
        self.d78 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d78.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d78.setText("")
        self.d78.setObjectName("d78")
        self.gridLayout_30.addWidget(self.d78, 2, 2, 1, 1)
        self.d74 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d74.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d74.setText("")
        self.d74.setObjectName("d74")
        self.gridLayout_30.addWidget(self.d74, 1, 1, 1, 1)
        self.d75 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d75.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d75.setText("")
        self.d75.setObjectName("d75")
        self.gridLayout_30.addWidget(self.d75, 1, 2, 1, 1)
        self.d72 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d72.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d72.setText("")
        self.d72.setObjectName("d72")
        self.gridLayout_30.addWidget(self.d72, 0, 2, 1, 1)
        self.d71 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d71.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d71.setText("")
        self.d71.setObjectName("d71")
        self.gridLayout_30.addWidget(self.d71, 0, 1, 1, 1)
        self.d70 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.d70.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d70.setText("")
        self.d70.setObjectName("d70")
        self.gridLayout_30.addWidget(self.d70, 0, 0, 1, 1)
        self.gridLayoutWidget_21 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_21.setGeometry(QtCore.QRect(10, 220, 201, 151))
        self.gridLayoutWidget_21.setObjectName("gridLayoutWidget_21")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.gridLayoutWidget_21)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.d14 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d14.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d14.setText("")
        self.d14.setObjectName("d14")
        self.gridLayout_25.addWidget(self.d14, 1, 1, 1, 1)
        self.d15 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d15.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d15.setText("")
        self.d15.setObjectName("d15")
        self.gridLayout_25.addWidget(self.d15, 1, 2, 1, 1)
        self.d10 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d10.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d10.setText("")
        self.d10.setObjectName("d10")
        self.gridLayout_25.addWidget(self.d10, 0, 0, 1, 1)
        self.d12 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d12.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d12.setText("")
        self.d12.setObjectName("d12")
        self.gridLayout_25.addWidget(self.d12, 0, 2, 1, 1)
        self.d11 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d11.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d11.setText("")
        self.d11.setObjectName("d11")
        self.gridLayout_25.addWidget(self.d11, 0, 1, 1, 1)
        self.d13 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d13.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d13.setText("")
        self.d13.setObjectName("d13")
        self.gridLayout_25.addWidget(self.d13, 1, 0, 1, 1)
        self.d16 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d16.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d16.setText("")
        self.d16.setObjectName("d16")
        self.gridLayout_25.addWidget(self.d16, 2, 0, 1, 1)
        self.d17 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d17.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d17.setText("")
        self.d17.setObjectName("d17")
        self.gridLayout_25.addWidget(self.d17, 2, 1, 1, 1)
        self.d18 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.d18.setStyleSheet("QLabel {\n"
"    background-color: #eaf6ff;\n"
"    border: 1px solid #3399ff;\n"
"    border-radius: 5px;\n"
"    color: #003366;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.d18.setText("")
        self.d18.setObjectName("d18")
        self.gridLayout_25.addWidget(self.d18, 2, 2, 1, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(510, 140, 291, 291))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.r03 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r03.setFont(font)
        self.r03.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r03.setText("")
        self.r03.setObjectName("r03")
        self.gridLayout_5.addWidget(self.r03, 0, 2, 1, 1)
        self.r02 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r02.setFont(font)
        self.r02.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r02.setText("")
        self.r02.setObjectName("r02")
        self.gridLayout_5.addWidget(self.r02, 0, 1, 1, 1)
        self.r01 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r01.setFont(font)
        self.r01.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r01.setText("")
        self.r01.setObjectName("r01")
        self.gridLayout_5.addWidget(self.r01, 0, 0, 1, 1)
        self.r05 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r05.setFont(font)
        self.r05.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r05.setText("")
        self.r05.setObjectName("r05")
        self.gridLayout_5.addWidget(self.r05, 1, 1, 1, 1)
        self.r06 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r06.setFont(font)
        self.r06.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r06.setText("")
        self.r06.setObjectName("r06")
        self.gridLayout_5.addWidget(self.r06, 1, 2, 1, 1)
        self.r04 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r04.setFont(font)
        self.r04.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r04.setText("")
        self.r04.setObjectName("r04")
        self.gridLayout_5.addWidget(self.r04, 1, 0, 1, 1)
        self.r07 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r07.setFont(font)
        self.r07.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r07.setText("")
        self.r07.setObjectName("r07")
        self.gridLayout_5.addWidget(self.r07, 2, 0, 1, 1)
        self.r08 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r08.setFont(font)
        self.r08.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r08.setText("")
        self.r08.setObjectName("r08")
        self.gridLayout_5.addWidget(self.r08, 2, 1, 1, 1)
        self.r09 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r09.setFont(font)
        self.r09.setStyleSheet("QLabel {\n"
"    background-color: #f0f8ff;       /* Màu nền xanh nhạt */\n"
"    border: 2px solid #4682b4;       /* Viền xanh đậm */\n"
"    border-radius: 8px;              /* Bo góc */\n"
"    color: #000080;                  /* Màu chữ xanh đậm */\n"
"    qproperty-alignment: AlignCenter; /* Căn giữa nội dung */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #dbeeff;       /* Hiệu ứng khi hover */\n"
"    border: 2px solid #1e90ff;\n"
"}\n"
"")
        self.r09.setText("")
        self.r09.setObjectName("r09")
        self.gridLayout_5.addWidget(self.r09, 2, 2, 1, 1)
        self.btnStart = QtWidgets.QPushButton(Frame)
        self.btnStart.setGeometry(QtCore.QRect(580, 540, 201, 51))
        self.btnStart.setStyleSheet("QPushButton {\n"
"    background-color: #00A8A8;         /* Xanh ngọc lam dịu */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008C8C;         /* Đậm hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #006F6F;         /* Đậm hơn nữa khi nhấn giữ */\n"
"}\n"
"")
        self.btnStart.setObjectName("btnStart")
        self.btnComplete = QtWidgets.QPushButton(Frame)
        self.btnComplete.setGeometry(QtCore.QRect(580, 700, 201, 51))
        self.btnComplete.setStyleSheet("QPushButton {\n"
"    background-color: #00A8A8;         /* Xanh ngọc lam dịu */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008C8C;         /* Đậm hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #006F6F;         /* Đậm hơn nữa khi nhấn giữ */\n"
"}\n"
"\n"
"")
        self.btnComplete.setObjectName("btnComplete")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(610, 460, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnReset = QtWidgets.QPushButton(Frame)
        self.btnReset.setGeometry(QtCore.QRect(580, 620, 201, 51))
        self.btnReset.setStyleSheet("QPushButton {\n"
"    background-color: #00A8A8;         /* Xanh ngọc lam dịu */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #008C8C;         /* Đậm hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #006F6F;         /* Đậm hơn nữa khi nhấn giữ */\n"
"}\n"
"")
        self.btnReset.setObjectName("btnReset")
        self.lblStep = QtWidgets.QLabel(Frame)
        self.lblStep.setGeometry(QtCore.QRect(690, 460, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStep.setFont(font)
        self.lblStep.setObjectName("lblStep")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_73.setText(_translate("Frame", "TextLabel"))
        self.label_74.setText(_translate("Frame", "TextLabel"))
        self.label_75.setText(_translate("Frame", "TextLabel"))
        self.label_76.setText(_translate("Frame", "TextLabel"))
        self.label_77.setText(_translate("Frame", "TextLabel"))
        self.label_78.setText(_translate("Frame", "TextLabel"))
        self.label_79.setText(_translate("Frame", "TextLabel"))
        self.label_80.setText(_translate("Frame", "TextLabel"))
        self.label_81.setText(_translate("Frame", "TextLabel"))
        self.label_100.setText(_translate("Frame", "TextLabel"))
        self.label_101.setText(_translate("Frame", "TextLabel"))
        self.label_102.setText(_translate("Frame", "TextLabel"))
        self.label_103.setText(_translate("Frame", "TextLabel"))
        self.label_104.setText(_translate("Frame", "TextLabel"))
        self.label_105.setText(_translate("Frame", "TextLabel"))
        self.label_106.setText(_translate("Frame", "TextLabel"))
        self.label_107.setText(_translate("Frame", "TextLabel"))
        self.label_108.setText(_translate("Frame", "TextLabel"))
        self.groupBox.setTitle(_translate("Frame", "Start State"))
        self.groupBox_3.setTitle(_translate("Frame", "Destination State"))
        self.btnStart.setText(_translate("Frame", "Start"))
        self.btnComplete.setText(_translate("Frame", "Complete"))
        self.label.setText(_translate("Frame", "STEP:"))
        self.btnReset.setText(_translate("Frame", "Reset"))
        self.lblStep.setText(_translate("Frame", "0"))
