# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StepsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1174, 691)
        Frame.setStyleSheet("color: #FF8C00;\n"
"")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(510, 30, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.btn_Complete = QtWidgets.QPushButton(Frame)
        self.btn_Complete.setGeometry(QtCore.QRect(440, 590, 421, 51))
        self.btn_Complete.setStyleSheet("QPushButton#btn_Complete {\n"
"    background-color: #E0E0E0;  /* Màu nền xám nhạt */\n"
"    color: #FF9800;             /* Màu chữ cam */\n"
"    font-size: 18px;            /* Cỡ chữ */\n"
"    font-weight: bold;          /* In đậm */\n"
"    padding: 12px 24px;         /* Lề trong */\n"
"    border-radius: 8px;         /* Bo góc */\n"
"    border: 2px solid #FF9800;  /* Viền màu cam */\n"
"}\n"
"\n"
"QPushButton#btn_Complete:hover {\n"
"    background-color: #FFCC80;  /* Khi hover thì nền cam nhạt */\n"
"    color: white;               /* Chữ trắng */\n"
"    border: 2px solid #FF9800;  /* Viền vẫn cam */\n"
"}\n"
"\n"
"QPushButton#btn_Complete:pressed {\n"
"    background-color: #F57C00;  /* Khi nhấn thì cam đậm hơn */\n"
"    color: white;\n"
"}\n"
"")
        self.btn_Complete.setObjectName("btn_Complete")
        self.txt_Steps = QtWidgets.QTextEdit(Frame)
        self.txt_Steps.setGeometry(QtCore.QRect(150, 110, 921, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Steps.setFont(font)
        self.txt_Steps.setObjectName("txt_Steps")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "DETAILED STEPS"))
        self.btn_Complete.setText(_translate("Frame", "Complete the review"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
